export {
  BATTLE_V2_QUALITY_PRESETS,
  BATTLE_V2_ACTIVE_WINDOW_MS,
  BATTLE_V2_ROSTER_LIMIT,
  BATTLE_V2_PLAYER_SPEED,
  BATTLE_V2_BULLET_SPEED,
  BATTLE_V2_ENEMY_BULLET_SPEED,
  BATTLE_V2_SHOT_COOLDOWN,
  BATTLE_V2_BOSS_MIN_INTERVAL_MS,
} from "../config";

export type { BattleV2Quality, BattleQualityPreset } from "../config";
