use super::*;

use crate::domain::entities::{
    AgentConversationWorkspaceMode, AgentWorkspacePrMetadataDecision, ArtifactId,
    IdeationAnalysisBaseRefKind, IdeationSessionId, ProjectId, TaskCategory,
};
use crate::tests::mock_github_service::MockGithubService;

fn agent_workspace_fixture() -> (ChatConversation, AgentConversationWorkspace) {
    let project_id = ProjectId::from_string("project-pr-publish".to_string());
    let mut conversation = ChatConversation::new_project(project_id.clone());
    conversation.title = Some("Conversation title".to_string());
    let workspace = AgentConversationWorkspace::new(
        conversation.id.clone(),
        project_id,
        AgentConversationWorkspaceMode::Edit,
        IdeationAnalysisBaseRefKind::ProjectDefault,
        "main".to_string(),
        Some("main".to_string()),
        Some("0".repeat(40)),
        "feature/pr-description".to_string(),
        "/tmp/pr-description-worktree".to_string(),
    );
    (conversation, workspace)
}

#[tokio::test]
async fn agent_workspace_publisher_creates_draft_with_generated_body() {
    let (conversation, workspace) = agent_workspace_fixture();
    let description = AgentWorkspacePrDescription::new(
        Some("Generated PR title".to_string()),
        "## Summary\n\nGenerated body".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(42, "https://github.com/mock/repo/pull/42");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let AgentWorkspacePrPublishResult::Published(outcome) = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap()
    else {
        panic!("new workspace should create a draft PR");
    };

    assert_eq!(outcome.pr_number, 42);
    assert!(outcome.created_pr);
    assert_eq!(outcome.pr_status, "draft");
    let state = github.state();
    let (base, head, title, body_path) = state
        .last_create_draft_pr_args
        .clone()
        .expect("draft PR args should be captured");
    assert_eq!(base, "main");
    assert_eq!(head, "feature/pr-description");
    assert_eq!(title, "Generated PR title");
    assert!(body_path.contains("tmp"));
    let body = state.last_create_draft_pr_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nGenerated body"));
    assert!(body.contains("_Generated by [RalphX]("));
    assert!(body.contains(RALPHX_MANAGED_PR_BODY_START));
    assert!(body.contains(RALPHX_MANAGED_PR_BODY_END));
}

#[tokio::test]
async fn agent_workspace_publisher_updates_existing_pr_with_title_fallback() {
    let (mut conversation, mut workspace) = agent_workspace_fixture();
    conversation.title = Some("Untitled agent".to_string());
    workspace.publication_pr_number = Some(77);
    workspace.publication_pr_url = Some("https://github.com/mock/repo/pull/77".to_string());
    let description =
        AgentWorkspacePrDescription::new(None, "## Summary\n\nUpdated body".to_string());
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let AgentWorkspacePrPublishResult::Published(outcome) = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap()
    else {
        panic!("open workspace PR should be updated");
    };

    assert_eq!(outcome.pr_number, 77);
    assert!(!outcome.created_pr);
    assert_eq!(outcome.pr_status, "open");
    assert_eq!(outcome.pr_url, "https://github.com/mock/repo/pull/77");
    let state = github.state();
    assert_eq!(state.update_pr_details_calls, 1);
    let (pr_number, title, body_path) = state
        .last_update_pr_details_args
        .clone()
        .expect("update PR args should be captured");
    assert_eq!(pr_number, 77);
    assert_eq!(title, "Agent conversation changes");
    assert!(body_path.contains("tmp"));
    let body = state.last_update_pr_details_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nUpdated body"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn agent_workspace_publisher_signals_terminal_identity_without_mutating_then_creates_after_clear(
) {
    let (conversation, mut workspace) = agent_workspace_fixture();
    workspace.publication_pr_number = Some(77);
    workspace.publication_pr_status = Some("closed".to_string());
    let description = AgentWorkspacePrDescription::new(
        Some("Fresh draft".to_string()),
        "## Summary\n\nFresh body".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(78, "https://github.com/mock/repo/pull/78");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    assert_eq!(
        publisher
            .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
            .await
            .unwrap(),
        AgentWorkspacePrPublishResult::TerminalPublicationIdentity
    );
    assert_eq!(github.state().update_pr_details_calls, 0);
    assert_eq!(github.state().create_draft_pr_calls, 0);

    workspace.publication_pr_number = None;
    workspace.publication_pr_url = None;
    workspace.publication_pr_status = None;
    workspace.publication_push_status = None;
    let AgentWorkspacePrPublishResult::Published(outcome) = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap()
    else {
        panic!("cleared publication identity should create a fresh draft PR");
    };
    assert_eq!(outcome.pr_number, 78);
    assert!(outcome.created_pr);
    assert_eq!(github.state().update_pr_details_calls, 0);
    assert_eq!(github.state().create_draft_pr_calls, 1);
}

#[tokio::test]
async fn agent_workspace_publisher_preserves_existing_pr_without_an_edit() {
    let (conversation, mut workspace) = agent_workspace_fixture();
    workspace.publication_pr_number = Some(77);
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let outcome = publisher
        .publish_existing_pr_metadata_decision(
            temp_dir.path(),
            &conversation,
            77,
            workspace.publication_pr_url.as_deref(),
            None,
            &AgentWorkspacePrMetadataDecision::Preserve,
        )
        .await
        .unwrap();

    assert_eq!(outcome.pr_number, 77);
    assert!(!outcome.created_pr);
    let state = github.state();
    assert_eq!(state.patch_pr_metadata_calls, 0);
    assert_eq!(state.update_pr_details_calls, 0);
    assert_eq!(state.create_draft_pr_calls, 0);
}

#[tokio::test]
async fn agent_workspace_publisher_uses_trusted_existing_pr_identity_without_workspace_linkage() {
    let (conversation, _workspace) = agent_workspace_fixture();
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let result = publisher
        .publish_existing_pr_metadata_decision(
            temp_dir.path(),
            &conversation,
            77,
            Some("https://github.com/mock/repo/pull/77"),
            None,
            &AgentWorkspacePrMetadataDecision::Preserve,
        )
        .await;

    assert!(result.is_ok());
    let state = github.state();
    assert_eq!(state.create_draft_pr_calls, 0);
    assert_eq!(state.update_pr_details_calls, 0);
    assert_eq!(state.patch_pr_metadata_calls, 0);
}

#[tokio::test]
async fn agent_workspace_publisher_patches_only_requested_existing_pr_metadata() {
    let (mut conversation, mut workspace) = agent_workspace_fixture();
    conversation.title = Some("rx-42: Fix composer references".to_string());
    workspace.publication_pr_number = Some(77);
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait)
        .with_plan_markdown("## Plan\n\nStep 1".to_string());
    let temp_dir = tempfile::tempdir().unwrap();

    publisher
        .publish_existing_pr_metadata_decision(
            temp_dir.path(),
            &conversation,
            77,
            None,
            None,
            &AgentWorkspacePrMetadataDecision::patch(
                Some("Fix composer references".to_string()),
                None,
            )
            .unwrap(),
        )
        .await
        .unwrap();

    let state = github.state();
    assert_eq!(state.patch_pr_metadata_calls, 1);
    assert_eq!(state.update_pr_details_calls, 0);
    let (_, title, body_path) = state
        .last_patch_pr_metadata_args
        .clone()
        .expect("metadata patch args should be captured");
    assert_eq!(title.as_deref(), Some("RX-42: Fix composer references"));
    assert_eq!(body_path, None);
    assert_eq!(state.last_patch_pr_metadata_body, None);
}

#[tokio::test]
async fn agent_workspace_publisher_body_only_patch_never_synthesizes_title() {
    let (conversation, mut workspace) = agent_workspace_fixture();
    workspace.publication_pr_number = Some(77);
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    publisher
        .publish_existing_pr_metadata_decision(
            temp_dir.path(),
            &conversation,
            77,
            None,
            None,
            &AgentWorkspacePrMetadataDecision::patch(None, Some("Updated body".to_string()))
                .unwrap(),
        )
        .await
        .unwrap();

    let state = github.state();
    let (_, title, body_path) = state
        .last_patch_pr_metadata_args
        .clone()
        .expect("metadata patch args should be captured");
    assert_eq!(title, None);
    assert!(body_path.is_some());
    let body = state.last_patch_pr_metadata_body.as_deref().unwrap();
    assert!(body.starts_with("Updated body"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn agent_workspace_publisher_patches_both_existing_pr_metadata_fields_once() {
    let (conversation, mut workspace) = agent_workspace_fixture();
    workspace.publication_pr_number = Some(77);
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    publisher
        .publish_existing_pr_metadata_decision(
            temp_dir.path(),
            &conversation,
            77,
            None,
            None,
            &AgentWorkspacePrMetadataDecision::patch(
                Some("Updated title".to_string()),
                Some("Updated body".to_string()),
            )
            .unwrap(),
        )
        .await
        .unwrap();

    let state = github.state();
    assert_eq!(state.patch_pr_metadata_calls, 1);
    let (_, title, body_path) = state
        .last_patch_pr_metadata_args
        .clone()
        .expect("metadata patch args should be captured");
    assert_eq!(title.as_deref(), Some("Updated title"));
    assert!(body_path.is_some());
}

#[tokio::test]
async fn agent_workspace_publisher_prefixes_pr_title_with_jira_key() {
    let (mut conversation, workspace) = agent_workspace_fixture();
    conversation.title = Some("rx-42: Fix composer references".to_string());
    let description = AgentWorkspacePrDescription::new(
        Some("Fix composer references".to_string()),
        "## Summary\n\nGenerated body".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(42, "https://github.com/mock/repo/pull/42");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let AgentWorkspacePrPublishResult::Published(outcome) = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap()
    else {
        panic!("new workspace should create a draft PR");
    };

    assert_eq!(outcome.pr_number, 42);
    let state = github.state();
    let (_, _, title, _) = state
        .last_create_draft_pr_args
        .clone()
        .expect("draft PR args should be captured");
    assert_eq!(title, "RX-42: Fix composer references");
}

#[tokio::test]
async fn agent_workspace_publisher_appends_plan_block_and_footer() {
    let (conversation, workspace) = agent_workspace_fixture();
    let description = AgentWorkspacePrDescription::new(
        Some("PR with plan".to_string()),
        "## Summary\n\nBody content".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(99, "https://github.com/mock/repo/pull/99");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait)
        .with_plan_markdown("## Plan\n\nStep 1\nStep 2".to_string());
    let temp_dir = tempfile::tempdir().unwrap();

    publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap();

    let state = github.state();
    let body = state.last_create_draft_pr_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nBody content"));
    assert!(body.contains("<details>\n<summary>View full plan</summary>"));
    assert!(body.contains("## Plan\n\nStep 1\nStep 2"));
    assert!(body.contains("</details>"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn plan_pr_publisher_uses_agent_body_and_ignores_repo_template() {
    let temp_dir = tempfile::tempdir().unwrap();
    let github_dir = temp_dir.path().join(".github");
    std::fs::create_dir_all(&github_dir).unwrap();
    std::fs::write(
        github_dir.join("PULL_REQUEST_TEMPLATE.md"),
        "## Checklist\n\n- [ ] Template item\n",
    )
    .unwrap();

    let project_id = ProjectId::from_string("project-plan-pr".to_string());
    let mut project = Project::new(
        "Plan project".to_string(),
        temp_dir.path().to_string_lossy().to_string(),
    );
    project.id = project_id.clone();
    project.base_branch = Some("main".to_string());
    let task = Task::new_with_category(
        project_id.clone(),
        "Merge plan".to_string(),
        TaskCategory::PlanMerge,
    );
    let mut plan_branch = PlanBranch::new(
        ArtifactId::from_string("artifact-plan".to_string()),
        IdeationSessionId::from_string("session-plan".to_string()),
        project_id,
        "feature/plan".to_string(),
        "develop".to_string(),
    );
    plan_branch.pr_number = Some(123);

    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = PlanPrPublisher::new(&github_trait, None, None);
    let description = AgentWorkspacePrDescription::new(
        None,
        "## Summary\n\nAgent-written plan PR body".to_string(),
    );

    publisher
        .sync_existing_pr(
            &task,
            &project,
            &plan_branch,
            PrReviewState::Ready,
            &description,
        )
        .await
        .unwrap();

    let state = github.state();
    assert_eq!(state.update_pr_details_calls, 1);
    let (pr_number, title, _) = state
        .last_update_pr_details_args
        .clone()
        .expect("update PR args should be captured");
    assert_eq!(pr_number, 123);
    assert_eq!(title, "Merge plan");
    let body = state.last_update_pr_details_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nAgent-written plan PR body"));
    assert!(!body.contains("## Checklist"));
    assert!(!body.contains("## RalphX Status"));
    assert!(!body.contains("## How To Review"));
    assert!(body.contains("_No plan artifact was available"));
    assert!(body.contains("<summary>View full plan</summary>"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn plan_pr_publisher_rejects_empty_agent_body() {
    let temp_dir = tempfile::tempdir().unwrap();
    let project_id = ProjectId::from_string("project-plan-pr".to_string());
    let mut project = Project::new(
        "Plan project".to_string(),
        temp_dir.path().to_string_lossy().to_string(),
    );
    project.id = project_id.clone();
    let task = Task::new_with_category(
        project_id.clone(),
        "Merge plan".to_string(),
        TaskCategory::PlanMerge,
    );
    let mut plan_branch = PlanBranch::new(
        ArtifactId::from_string("artifact-plan".to_string()),
        IdeationSessionId::from_string("session-plan".to_string()),
        project_id,
        "feature/plan".to_string(),
        "main".to_string(),
    );
    plan_branch.pr_number = Some(123);

    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = PlanPrPublisher::new(&github_trait, None, None);
    let description = AgentWorkspacePrDescription::new(None, "   \n".to_string());

    let result = publisher
        .sync_existing_pr(
            &task,
            &project,
            &plan_branch,
            PrReviewState::Ready,
            &description,
        )
        .await;

    match result {
        Err(AppError::Infrastructure(message)) => {
            assert_eq!(message, "plan PR describer returned an empty PR body");
        }
        Err(other) => panic!("expected infrastructure error, got {other:?}"),
        Ok(_) => panic!("empty agent body should fail before writing PR details"),
    }
    assert_eq!(github.state().update_pr_details_calls, 0);
}

#[test]
fn finalize_body_without_plan_appends_only_footer() {
    let body = finalize_agent_workspace_pr_body("## Summary\n\nBody", &None);
    assert_eq!(
        body,
        format!(
            "## Summary\n\nBody\n\n{RALPHX_MANAGED_PR_BODY_START}\n\
             {RALPHX_GENERATED_FOOTER}\n{RALPHX_MANAGED_PR_BODY_END}"
        )
    );
    assert!(!body.contains("<details>"));
}

#[test]
fn finalize_body_without_plan_wraps_an_existing_canonical_footer_once() {
    let input = format!("## Summary\n\nBody\n\n{RALPHX_GENERATED_FOOTER}\n");

    let body = finalize_agent_workspace_pr_body(&input, &None);

    assert_eq!(
        body,
        format!(
            "## Summary\n\nBody\n\n{RALPHX_MANAGED_PR_BODY_START}\n\
             {RALPHX_GENERATED_FOOTER}\n{RALPHX_MANAGED_PR_BODY_END}"
        )
    );
    assert_eq!(body.matches(RALPHX_GENERATED_FOOTER).count(), 1);
}

#[test]
fn finalize_body_with_empty_plan_appends_only_footer() {
    let body = finalize_agent_workspace_pr_body("## Summary\n\nBody", &Some("  ".to_string()));
    assert_eq!(
        body,
        format!(
            "## Summary\n\nBody\n\n{RALPHX_MANAGED_PR_BODY_START}\n\
             {RALPHX_GENERATED_FOOTER}\n{RALPHX_MANAGED_PR_BODY_END}"
        )
    );
    assert!(!body.contains("<details>"));
}

/// A degraded describe step publishes an empty editable body on purpose: the managed content is
/// the whole PR body, and it must never come back empty.
#[test]
fn finalize_empty_body_without_plan_still_yields_managed_content() {
    let body = finalize_agent_workspace_pr_body("", &None);

    assert_eq!(
        body,
        format!(
            "\n\n{RALPHX_MANAGED_PR_BODY_START}\n\
             {RALPHX_GENERATED_FOOTER}\n{RALPHX_MANAGED_PR_BODY_END}"
        )
    );
    assert!(!body.trim().is_empty());
    assert!(!body.contains("<details>"));
}

#[test]
fn finalize_empty_body_with_plan_yields_the_plan_section_and_footer() {
    let body = finalize_agent_workspace_pr_body("", &Some("# Plan\n\nDo the thing".to_string()));

    assert!(body.starts_with(&format!("\n\n{RALPHX_MANAGED_PR_BODY_START}\n")));
    assert!(body.contains("<summary>View full plan</summary>"));
    assert!(body.contains("# Plan\n\nDo the thing"));
    assert!(body.contains(RALPHX_GENERATED_FOOTER));
    assert!(body.chars().count() <= GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
}

#[test]
fn oversized_plan_body_keeps_the_canonical_footer_after_truncation() {
    let prefix = "## Summary\n\n<details>\n\n";
    let suffix = format!("\n\n</details>\n\n{RALPHX_GENERATED_FOOTER}");

    let body = fit_plan_markdown_to_pr_body(prefix, &"x".repeat(60_000), &suffix);

    assert_eq!(body.chars().count(), GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
    assert!(body.contains(PR_BODY_TRUNCATION_NOTICE.trim()));
    assert!(body.contains(RALPHX_GENERATED_FOOTER));
}

#[tokio::test]
async fn existing_body_patch_recomposes_the_exact_remote_managed_and_trailing_suffix() {
    let (conversation, _workspace) = agent_workspace_fixture();
    let remote_body = format!(
        "Old editable body\n\n{RALPHX_MANAGED_PR_BODY_START}\n\
         <details>\n<summary>View full plan</summary>\n\nOriginal plan\n</details>\n\n\
         {RALPHX_GENERATED_FOOTER}\n{RALPHX_MANAGED_PR_BODY_END}\n\nCodeSmith tail  \n"
    );
    let expected_suffix = decompose_ralphx_managed_pr_body(&remote_body)
        .preserved_suffix
        .unwrap()
        .to_string();
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait)
        .with_plan_markdown("A newer plan that must not replace the remote plan".to_string());
    let temp_dir = tempfile::tempdir().unwrap();

    publisher
        .publish_existing_pr_metadata_decision(
            temp_dir.path(),
            &conversation,
            77,
            None,
            Some(&remote_body),
            &AgentWorkspacePrMetadataDecision::patch(
                None,
                Some("New editable body  \n".to_string()),
            )
            .unwrap(),
        )
        .await
        .unwrap();

    let published = github
        .state()
        .last_patch_pr_metadata_body
        .clone()
        .expect("body patch should be captured");
    assert_eq!(published, format!("New editable body{expected_suffix}"));
    assert!(!published.contains("A newer plan"));
}

#[test]
fn preserved_suffix_budget_truncates_only_the_new_editable_prefix() {
    let suffix = format!(
        "\n\n{RALPHX_MANAGED_PR_BODY_START}\n{}\n{RALPHX_MANAGED_PR_BODY_END}",
        "s".repeat(GITHUB_PR_BODY_SOFT_LIMIT_CHARS - 200)
    );

    let body = recompose_agent_workspace_pr_body_with_preserved_suffix(&"e".repeat(1_000), &suffix)
        .unwrap();

    assert_eq!(body.chars().count(), GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
    assert!(body.contains(PR_BODY_TRUNCATION_NOTICE.trim()));
    assert!(body.ends_with(&suffix));
}

#[test]
fn finalized_agent_workspace_body_preserves_managed_markers_at_the_soft_limit() {
    for plan in [None, Some("Plan body".repeat(500))] {
        let body = finalize_agent_workspace_pr_body(&"e".repeat(60_000), &plan);

        assert_eq!(body.chars().count(), GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
        assert!(body.contains(PR_BODY_TRUNCATION_NOTICE.trim()));
        assert!(body.contains(RALPHX_GENERATED_FOOTER));
        assert!(body.ends_with(RALPHX_MANAGED_PR_BODY_END));
    }
}
