// TaskQA entity - QA artifacts for a task
// Stores acceptance criteria, test steps, and test results

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::{TaskId, TaskQAId};
use crate::domain::qa::{AcceptanceCriteria, QAResults, QATestSteps};

/// QA artifacts for a task
///
/// Stores all QA-related data across the three phases:
/// 1. QA Prep: Generates acceptance criteria and initial test steps
/// 2. QA Refinement: Updates test steps based on actual implementation
/// 3. QA Testing: Executes tests and stores results
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskQA {
    /// Unique identifier for this QA record
    pub id: TaskQAId,
    /// The task this QA data belongs to
    pub task_id: TaskId,

    // ----- Phase 1: QA Prep -----
    /// Acceptance criteria generated by QA Prep agent
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acceptance_criteria: Option<AcceptanceCriteria>,
    /// Initial test steps generated by QA Prep agent
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qa_test_steps: Option<QATestSteps>,
    /// ID of the agent that performed QA prep
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prep_agent_id: Option<String>,
    /// When QA prep started
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prep_started_at: Option<DateTime<Utc>>,
    /// When QA prep completed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prep_completed_at: Option<DateTime<Utc>>,

    // ----- Phase 2: QA Refinement -----
    /// Summary of what was actually implemented (from git diff)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_implementation: Option<String>,
    /// Test steps updated based on actual implementation
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refined_test_steps: Option<QATestSteps>,
    /// ID of the agent that performed refinement
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refinement_agent_id: Option<String>,
    /// When refinement completed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refinement_completed_at: Option<DateTime<Utc>>,

    // ----- Phase 3: QA Testing -----
    /// Test execution results
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub test_results: Option<QAResults>,
    /// Paths to captured screenshots
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub screenshots: Vec<String>,
    /// ID of the agent that executed tests
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub test_agent_id: Option<String>,
    /// When testing completed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub test_completed_at: Option<DateTime<Utc>>,

    /// When this record was created
    pub created_at: DateTime<Utc>,
}

impl TaskQA {
    /// Create a new TaskQA record for a task
    pub fn new(task_id: TaskId) -> Self {
        Self {
            id: TaskQAId::new(),
            task_id,
            acceptance_criteria: None,
            qa_test_steps: None,
            prep_agent_id: None,
            prep_started_at: None,
            prep_completed_at: None,
            actual_implementation: None,
            refined_test_steps: None,
            refinement_agent_id: None,
            refinement_completed_at: None,
            test_results: None,
            screenshots: Vec::new(),
            test_agent_id: None,
            test_completed_at: None,
            created_at: Utc::now(),
        }
    }

    /// Create a TaskQA with a specific ID (for testing or database restoration)
    pub fn with_id(id: TaskQAId, task_id: TaskId) -> Self {
        let mut qa = Self::new(task_id);
        qa.id = id;
        qa
    }

    // ----- Phase 1: QA Prep Methods -----

    /// Start QA prep phase
    pub fn start_prep(&mut self, agent_id: String) {
        self.prep_agent_id = Some(agent_id);
        self.prep_started_at = Some(Utc::now());
    }

    /// Complete QA prep phase with generated criteria and steps
    pub fn complete_prep(&mut self, criteria: AcceptanceCriteria, steps: QATestSteps) {
        self.acceptance_criteria = Some(criteria);
        self.qa_test_steps = Some(steps);
        self.prep_completed_at = Some(Utc::now());
    }

    /// Check if QA prep is complete
    pub fn is_prep_complete(&self) -> bool {
        self.prep_completed_at.is_some()
    }

    /// Check if QA prep is in progress
    pub fn is_prep_in_progress(&self) -> bool {
        self.prep_started_at.is_some() && self.prep_completed_at.is_none()
    }

    // ----- Phase 2: QA Refinement Methods -----

    /// Complete refinement phase with implementation summary and refined steps
    pub fn complete_refinement(
        &mut self,
        agent_id: String,
        actual_implementation: String,
        refined_steps: QATestSteps,
    ) {
        self.refinement_agent_id = Some(agent_id);
        self.actual_implementation = Some(actual_implementation);
        self.refined_test_steps = Some(refined_steps);
        self.refinement_completed_at = Some(Utc::now());
    }

    /// Check if refinement is complete
    pub fn is_refinement_complete(&self) -> bool {
        self.refinement_completed_at.is_some()
    }

    /// Get the test steps to use (refined if available, otherwise initial)
    pub fn effective_test_steps(&self) -> Option<&QATestSteps> {
        self.refined_test_steps
            .as_ref()
            .or(self.qa_test_steps.as_ref())
    }

    // ----- Phase 3: QA Testing Methods -----

    /// Start test execution
    pub fn start_testing(&mut self, agent_id: String) {
        self.test_agent_id = Some(agent_id);
    }

    /// Complete testing with results
    pub fn complete_testing(&mut self, results: QAResults) {
        self.test_results = Some(results);
        self.test_completed_at = Some(Utc::now());
    }

    /// Add a screenshot path
    pub fn add_screenshot(&mut self, path: String) {
        self.screenshots.push(path);
    }

    /// Check if testing is complete
    pub fn is_testing_complete(&self) -> bool {
        self.test_completed_at.is_some()
    }

    /// Check if tests passed
    pub fn is_passed(&self) -> bool {
        self.test_results
            .as_ref()
            .map(|r| r.is_passed())
            .unwrap_or(false)
    }

    /// Check if tests failed
    pub fn is_failed(&self) -> bool {
        self.test_results
            .as_ref()
            .map(|r| r.is_failed())
            .unwrap_or(false)
    }
}

#[cfg(test)]
#[path = "task_qa_tests.rs"]
mod tests;
